package filmes;

public enum Genero {

	SUSPENSE, DRAMA, ACAO, AVENTURA, ROMANCE, 
	COMEDIA, TERROR, FICCAO_CIENTIFICA, BIOGRAFIA, 
	COMEDIA_DRAMATICA, COMEDIA_ROMANTICA, HISTORIA, 
	FANTASIA, MUSICAL, GUERRA;
	
}